<?php

/**
 * @file
 * Allows users to specify a representative image for a content type by choosing
 * which image field contains the appropriate image.
 */

/**
 * Implements hook_form_alter().
 */
function representative_image_form_node_type_form_alter(&$form, &$form_state) {
  if (isset($form['#node_type']->type)) {
    $bundle = $form['#node_type']->type;
  }
  else {
    return;
  }

  $type = 'node';
  $form_state['representative_image'] = array(
    'entity_type' => $type,
    'bundle' => $bundle,
  );

  $options = representative_image_available_fields($type, $bundle);
  $form['representative_image_fieldset'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#title' => t('Representative image'),
    '#group' => 'additional_settings',
    'representative_image' => array(
      '#type' => 'select',
      '#options' => $options,
      '#empty_option' => t('None'),
      '#empty_value' => 0,
      '#default_value' => representative_image_get_field($type, $bundle),
    ),
  );

  if (count($options)) {
    $form['representative_image_fieldset']['#description'] = t('Select a representative image for this node type, which will then be available in a token. See README.txt of the representative_image module for details.');
    $form['#submit'][] = 'representative_image_content_type_form_submit_handler';
  }
  else {
    $form['representative_image_fieldset']['#description'] = t('Please define at least one image field for this content type to define a representative image.');
  }
}

/**
 * Submit handler for the node type form.
 */
function representative_image_content_type_form_submit_handler($form, &$form_state) {
  $info = $form_state['representative_image'];
  if (isset($info['entity_type']) && isset($info['bundle'])) {
    $field = $form_state['values']['representative_image'];
    representative_image_set_field($info['entity_type'], $info['bundle'], $field);
  }
}

/**
 * Implements hook_token_info().
 */
function representative_image_token_info() {
  $node['representative_image'] = array(
    'name' => t('Representative image'),
    'description' => t('Replaced with an image from a node\'s field as defined in admin/structure/types/manage/my_content_type'),
  );

  return array(
    'tokens' => array('node' => $node),
  );
}

/**
 * Implements hook_tokens().
 */
function representative_image_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  if ($type == 'node' && !empty($data['node'])) {
    $node = $data['node'];

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'representative_image':
          $replacements[$original] = representative_image($node, $type);
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_features_pipe_alter().
 */
function representative_image_features_pipe_alter(&$pipe, $data, $export) {
  if (module_exists('strongarm') && $export['component'] == 'node') {
    foreach ($data as $content_type) {
      $pipe['variable'][] = 'representative_image_field_node_' . $content_type;
    }
  }
}

/**
 * Implements hook_views_api().
 */
function representative_image_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'representative_image'),
  );
}

/**
 * Given a node object, returns a representative image as an absolute URL.
 *
 * If anything goes wrong, returns the value of the variable.
 *
 * @param $node
 *   A node object
 *
 * @return
 *   A string with a representative image as a fully formed absolute URL or an
 *   empty string if nothing could be found.
 */
function representative_image($entity, $type) {
  $image = '';

  if ($bundle = field_extract_bundle($type, $entity)) {
    if ($field = representative_image_get_field($type, $bundle)) {
      $field_items = field_get_items($type, $entity, $field);
      if(is_array($field_items) && count($field_items) && isset($field_items[0]['uri'])) {
        $image = file_create_url($field_items[0]['uri']);
      }
    }
  }

  // If we don't have anything here, try to get the default image for info on
  // how to set the default image, See the README.txt file.
  // @todo: Is there a better way to handle this?
  if (!$image) {
    global $base_url;
    $image = $base_url . '/' . variable_get('representative_image_default', '');
  }

  return $image;
}

/**
 * Given a node type machine name, returns available image fields.
 */
function representative_image_available_fields($type, $bundle) {
  $fields = array();

  foreach (field_info_instances($type, $bundle) as $name => $info) {
    $supported_widget_types = array(
      'image_image',
      'media_generic',
    );

    if (isset($info['widget']['type']) && in_array($info['widget']['type'], $supported_widget_types)) {
      $fields[$name] = $info['label'] . ' (' . $name . ')';
    }
  }
  return $fields;
}

/**
 * Given a node type, return its representative image field if it exists, NULL
 * otherwise.
 */
function representative_image_get_field($type, $bundle) {
  $field = variable_get('representative_image_field_' . $type . '_' . $bundle, '');
  return array_key_exists($field, representative_image_available_fields($type, $bundle)) ? $field : NULL;
}

/**
 * Set the default field for a given node.
 */
function representative_image_set_field($type, $bundle, $field) {
  variable_set('representative_image_field_' . $type . '_' . $bundle, $field);
}

/**
 * Helper function to help you set this up without pointing and clicking.
 *
 * Install the devel module, go to devel/php and type in
 * dpm(_representative_image_deploy_helper()); then copy paste the result in a
 * hook_update_n() function. Edit it there, and finally update your database
 * with drush updb or by visiting update.php.
 * @todo: there must be a better way to handle this.
 */
function _representative_image_deploy_helper() {
  $node_types = node_type_get_types();
  $lines = array();
  $lines[] = '/**';
  $lines[] = ' * Implements hook_update_n(). Set up representative images';
  $lines[] = ' */';
  $lines[] = 'function mymodule_update_7005() {';
  $lines[] = '  variable_set(\'representative_image_default\', \'sites/default/files/path/to/default.png\');';
  $lines[] = '  variable_set(\'representative_image_fields\', array(\'node\' => array(';
  foreach ($node_types as $type => $object) {
    $available_fields = array_keys(representative_image_available_fields($type));
    $lines[] = '    \'' . $type . '\' => \'' . implode('|', $available_fields) . '\',';
  }
  $lines[] = '  )));';
  $lines[] = '}';
  return implode('
', $lines);
}
