<?php

/**
 * @file
 * Primary module hooks for Representative Image module.
 *
 * @TODO the following code is pending to port.
 */

///**
// * Implements hook_form_alter().
// */
//function representative_image_form_node_type_form_alter(&$form, &$form_state) {
//  if (!isset($form['#node_type']->type)) {
//    return;
//  }
//
//  $type = 'node';
//  $bundle = $form['#node_type']->type;
//
//  // Add a responsive image fieldset.
//  form_load_include($form_state, 'inc', 'representative_image', 'representative_image.admin');
//  representative_image_entity_settings_form($form, $form_state, 'node', entity_get_info('node'), array($bundle));
//
//  // Add handling for the vertical tabs js.
//  $form['#attached']['js'][] = drupal_get_path('module', 'representative_image') . '/js/representative_image.js';
//
//  // Adjust the fieldset.
//  $form[$type]['#title'] = t('Representative image');
//  $form[$type]['#group'] = 'additional_settings';
//}
//
///**
// * Implements hook_token_info().
// */
//function representative_image_token_info() {
//  $tokens = array();
//
//  $entities = entity_get_info();
//  foreach ($entities as $entity_name => $entity) {
//    $info['representative_image'] = array(
//      'name' => t('Representative image'),
//      'description' => format_string('Replaced with an image from a @name\'s field as defined !here.', array('@name' => $entity_name, '!here' => l(t('here'), '/admin/config/media/representative_image'))),
//    );
//    $tokens[$entity_name] = $info;
//  }
//
//  return array(
//    'tokens' => $tokens,
//  );
//}
//
///**
// * Implements hook_tokens().
// */
//function representative_image_tokens($type, $tokens, array $data = array(), array $options = array()) {
//  $replacements = array();
//
//  $entities = entity_get_info();
//  foreach ($entities as $entity_name => $entity) {
//    if ($type == $entity_name && !empty($data[$entity_name])) {
//      $entity_object = $data[$entity_name];
//
//      foreach ($tokens as $name => $original) {
//        switch ($name) {
//          case 'representative_image':
//            $replacements[$original] = representative_image($entity_object, $type);
//            break;
//        }
//      }
//    }
//  }
//
//  return $replacements;
//}
//
///**
// * Implements hook_features_pipe_alter().
// */
//function representative_image_features_pipe_alter(&$pipe, $data, $export) {
//  if (module_exists('strongarm') && $export['component'] == 'node') {
//    foreach ($data as $content_type) {
//      $pipe['variable'][] = 'representative_image_field_node_' . $content_type;
//    }
//  }
//}
//
///**
// * Implements hook_views_api().
// */
//function representative_image_views_api() {
//  return array(
//    'api' => 3,
//    'path' => drupal_get_path('module', 'representative_image') . '/views',
//  );
//}
//
