id: d7_representative_image_field_storage_config
label: Representative Image field storage configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: d7_representative_image_field_storage_config
  constants:
    status: true
    langcode: und
    type: representative_image
    cadinality: 1
    field_name: field_representative_image
process:
  entity_type: entity_type
  status: 'constants/status'
  langcode: 'constants/langcode'
  field_name: 'constants/field_name'
  type: 'constants/type'
  cardinality: 'constants/cardinality'
destination:
  plugin: entity:field_storage_config
migration_dependencies:
  optional:
    - d7_node_type
    - d7_field_instance
