id: d7_representative_image_field_config
label: Representative Image field config instances
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: d7_representative_image_field_config
  constants:
    status: true
    type: representative_image
    label: 'Representative image'
    field_name: field_representative_image
process:
  type: 'constants/type'
  field_name: 'constants/field_name'
  entity_type: entity_type
  bundle: bundle
  label: 'constants/label'
  settings: settings
  status: 'constants/status'
  langcode: 'constants/langcode'
destination:
  plugin: entity:field_config
migration_dependencies:
  required:
    - d7_representative_image_field_storage_config

